version: '3.7'
services:
  app:
    build:
      context: .
    image: off-the-shelf-object-detector:latest
    command: ["uvicorn", "app:app", "--host=0", "--reload"]
    ports:
      - '127.0.0.1:${PORT:-8000}:8000'
    volumes:
      - ./app:/app
